#!/usr/bin/env bash

cd ./flakes/birdeevim &&\
git add . &&\
nix flake update &&\
git add . &&\
cd ../..

which home-manager ||\
nix shell home-manager

git add . &&\
nix flake update &&\
sudo nixos-rebuild switch --show-trace --flake .#$1 &&\
home-manager switch --show-trace --flake .#$2 &&\
git add .
