#!/usr/bin/env bash
IFS='@' read -ra parts <<< "$1"
hostname="${parts[1]}"
fullfirst="$1"
shift 1

[ -n "$1" ] && [ "$1" == "up" ] && isUp="-u" && shift 1

prevWD=$(pwd)
NH_FLAKE=${NH_FLAKE:-"$(realpath "$(dirname "$(readlink -f "$0")")")/.."} && export NH_FLAKE &&\
cd "$NH_FLAKE" &&\
nix --extra-experimental-features "nix-command flakes pipe-operators" run nixpkgs#git -- add .
cd "$prevWD" &&\
nix --extra-experimental-features "nix-command flakes pipe-operators" run nixpkgs#nh -- os switch -v $isUp -H "$hostname" -- --show-trace "$@" &&\
nix --extra-experimental-features "nix-command flakes pipe-operators" run nixpkgs#nh -- home switch -v -b hm_bkp -c "$fullfirst" -- --show-trace "$@" &&\
cd "$NH_FLAKE" &&\
nix --extra-experimental-features "nix-command flakes pipe-operators" run nixpkgs#git -- add .
cd "$prevWD"
