#!/usr/bin/env bash
IFS='@' read -ra parts <<< "$1"
hostname="${parts[1]}"
fullfirst="$1"
shift 1

[ -n "$1" ] && [ "$1" == "up" ] && isUp="-u" && shift 1

prevWD=$(pwd)
FLAKE=${FLAKE:-"$(realpath "$(dirname "$(readlink -f "$0")")")/.."} && export FLAKE &&\
cd "$FLAKE" &&\
git add .
cd "$prevWD" &&\
nix run nixpkgs#nh -- os switch -v $isUp -H "$hostname" -- --show-trace "$@" &&\
nix run nixpkgs#nh -- home switch -v -b hm_bkp -c "$fullfirst" -- --show-trace "$@" &&\
cd "$FLAKE" &&\
git add .
cd "$prevWD"
