#!/usr/bin/env bash
IFS='@' read -ra parts <<< "$1"
hostname="${parts[1]}"

# nix --experimental-features flakes --extra-experimental-features nix-command flake update &&\
# git add . &&\
sudo nixos-rebuild switch --show-trace --flake .#$hostname &&\
nix --experimental-features flakes --extra-experimental-features nix-command run home-manager -- switch --show-trace --flake .#$1
