#!/usr/bin/env bash

[ -n "$1" ] && cfgOutput=$1 && shift 1 &&\
[ -n "$1" ] && [ "$1" == "up" ] && isUp="-u" && shift 1

prevWD=$(pwd)
FLAKE=${FLAKE:-$(realpath .)} && export FLAKE &&\
cd $FLAKE &&\
git add .
cd "$prevWD" &&\
nix run nixpkgs#nh -- home switch -v -b hm_bkp $isUp -c "$cfgOutput" -- --show-trace "$@" &&\
cd $FLAKE &&\
git add .
cd "$prevWD"
