#!/usr/bin/env bash
system=$1
installername=$2
FLAKE=${FLAKE:-"$(realpath "$(dirname "$(readlink -f "$0")")")/.."} &&\
nix --extra-experimental-features "nix-command flakes" build "$FLAKE#legacyPackages.${system}.nixosConfigurations.${installername}.config.system.build.isoImage"
# sudo dd if=./result/iso/something.iso of=/dev/sdd bs=1M status=progress
