#!/usr/bin/env bash
system=$1
installername=$2
nix build ".#legacyPackages.${system}.nixosConfigurations.${installername}.config.system.build.isoImage"
# sudo dd if=./result/iso/something.iso of=/dev/sdd bs=1M status=progress
