#!/usr/bin/env bash
IFS='@' read -ra parts <<< "$1"
hostname="${parts[1]}"
fullfirst="$1"
shift 1

[ -n "$1" ] && [ "$1" == "up" ] && isUp="-u" && shift 1

git add . &&\
FLAKE=${FLAKE:-$(realpath .)} && export FLAKE &&\
nix run nixpkgs#nh -- os switch -v $isUp -H "$hostname" -- --show-trace "$@" &&\
nix run nixpkgs#nh -- home switch -v -b hm_bkp $isUp -c "$fullfirst" -- --show-trace "$@" &&\
git add .
