#!/usr/bin/env bash

[ -n "$1" ] && hostname=$1 && shift 1 &&\
[ -n "$1" ] && [ "$1" == "up" ] && isUp="-u" && shift 1

prevWD=$(pwd)
FLAKE=${FLAKE:-"$(realpath "$(dirname "$(readlink -f "$0")")")/.."} && export FLAKE &&\
cd "$FLAKE" &&\
nix --extra-experimental-features "nix-command flakes" run nixpkgs#git -- add .
cd "$prevWD" &&\
nix --extra-experimental-features "nix-command flakes" run nixpkgs#nh -- os switch -v $isUp -H "$hostname" -- --show-trace "$@" &&\
cd "$FLAKE" &&\
nix --extra-experimental-features "nix-command flakes" run nixpkgs#git -- add .
cd "$prevWD"
