#!/usr/bin/env bash
IFS='@' read -ra parts <<< "$1"
hostname="${parts[1]}"

git add . &&\
[ -n $2 ] && [ "$2" == "-up" ] &&\
nix flake update
sudo nixos-rebuild switch --show-trace --flake .#$hostname &&\
git add .
