#!/usr/bin/env bash

prevWD=$(pwd)
FLAKE=${FLAKE:-"$(realpath "$(dirname "$(readlink -f "$0")")")/.."} && export FLAKE &&\
cd "$FLAKE" &&\
git add . &&\
cd "$prevWD" &&\
nixos-rebuild build-vm --flake "$FLAKE#$1"
